apiVersion: v1
kind: Service
metadata:
  name: echo2
spec:
  selector:
    app: echo2
  ports:
  - protocol: TCP
    name: web
    port: 8080

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo2
spec:
  hosts:
  - api.xiaowenx.com
  - api1.xiaowenx.com
  - api2.xiaowenx.com
  gateways:
  - api.default
  - api1.default
  - api2.default
  http:
  - match:
    - uri:
        prefix: /echo2
    route:
    - destination:
        port:
          number: 8080
        host: echo2
