apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo2
  template:
    metadata:
      labels:
        app: echo2
    spec:
      containers:
      - name: echo-info
        image: gcr.io/xiaowen/echo-info
        env:
        - name: FLASK_APP
          value: "src/main.py"
        - name: CLUSTER
          value: gke1
        command: ["flask"]
        args: ["run", "--host=0.0.0.0", "--port=8080"]
